-- 코드를 입력하세요
-- 중고거래 게시판 정보를 담은 USED_GOODS_BOARD -> 게시글
-- 중고거래 게시판 첨부파일 정보를 담은 USED_GOODS_REPLY -> 댓글

-- 댓글 조회
SELECT B.TITLE
        , A.BOARD_ID
        , A.REPLY_ID
        , A.WRITER_ID
        , A.CONTENTS
        , DATE_FORMAT(A.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY A
JOIN USED_GOODS_BOARD B
    ON A.BOARD_ID = B.BOARD_ID
WHERE SUBSTR(B.CREATED_DATE,1,7) = '2022-10'
ORDER 
    BY A.CREATED_DATE ASC, B.TITLE ASC;